// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(PegiDbContext))]
    [Migration("20220706202945_Proposal")]
    partial class Proposal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.City", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city_code");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("department_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city_name");

                    b.HasKey("Code")
                        .HasName("pk_cities");

                    b.HasIndex("DepartmentCode")
                        .HasDatabaseName("ix_cities_department_code");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_name");

                    b.HasKey("Code")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Entities.CV", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cv_code");

                    b.Property<string>("AttachFiles")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cv_attach_files");

                    b.HasKey("Code")
                        .HasName("pk_cv");

                    b.ToTable("cv", (string)null);
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("department_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("department_name");

                    b.HasKey("Code")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Entities.LineInvestigation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lines_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lines_name");

                    b.HasKey("Code")
                        .HasName("pk_lines");

                    b.ToTable("lines", (string)null);
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<string>("Document")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("person_document");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("person_birth_date");

                    b.Property<string>("CivilState")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_civil_state");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country_code");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_first_last_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_first_name");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_identification_type");

                    b.Property<string>("InstitutionalMail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_institutional_email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_phone");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("longtext")
                        .HasColumnName("person_second_last_name");

                    b.Property<string>("SecondName")
                        .HasColumnType("longtext")
                        .HasColumnName("person_second_name");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_sex");

                    b.HasKey("Document")
                        .HasName("pk_people");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_people_country_code");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Entities.Program", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("program_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("program_name");

                    b.HasKey("Code")
                        .HasName("pk_program");

                    b.ToTable("program", (string)null);
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_code");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_content");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_title");

                    b.HasKey("Code")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Entities.Proposal", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("proposals_code");

                    b.Property<string>("ApproachProblem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_approach_problem");

                    b.Property<string>("Bibliography")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_bibliography");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("proposals_date");

                    b.Property<string>("FormulationProblem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_formulation_problem");

                    b.Property<string>("GeneralObjective")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_general_objective");

                    b.Property<string>("JustificationProblem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_justification_problem");

                    b.Property<string>("ResearchGroup")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_research_group");

                    b.Property<string>("SpecificObjective")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_specific_objective");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposals_title");

                    b.HasKey("Code")
                        .HasName("pk_proposals");

                    b.ToTable("proposals", (string)null);
                });

            modelBuilder.Entity("Entities.ProposalEvaluation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("proposal_evaluation_code");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposal_evaluation_feedback");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proposal_evaluation_status");

                    b.HasKey("Code")
                        .HasName("pk_proposal_evaluation");

                    b.ToTable("proposal_evaluation", (string)null);
                });

            modelBuilder.Entity("Entities.Study", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("study_code");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city_code");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("study_end_date");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("study_institution");

                    b.Property<string>("PersonDocument1")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("person_document1");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("study_start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("study_type");

                    b.HasKey("Code")
                        .HasName("pk_studies");

                    b.HasIndex("CityCode")
                        .HasDatabaseName("ix_studies_city_code");

                    b.HasIndex("PersonDocument1")
                        .HasDatabaseName("ix_studies_person_document1");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Entities.SublineInvestigation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sublines_code");

                    b.Property<string>("LineInvestigationCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("line_investigation_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sublines_name");

                    b.HasKey("Code")
                        .HasName("pk_sublines");

                    b.HasIndex("LineInvestigationCode")
                        .HasDatabaseName("ix_sublines_line_investigation_code");

                    b.ToTable("sublines", (string)null);
                });

            modelBuilder.Entity("Entities.ThematicArea", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("thematic-areas_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("thematic-areas_name");

                    b.Property<string>("SublineInvestigationCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subline_investigation_code");

                    b.HasKey("Code")
                        .HasName("pk_thematic_areas");

                    b.HasIndex("SublineInvestigationCode")
                        .HasDatabaseName("ix_thematic_areas_subline_investigation_code");

                    b.ToTable("thematic-areas");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_password");

                    b.Property<string>("PersonDocument")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("person_document");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_role");

                    b.HasKey("Code")
                        .HasName("pk_users");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.HasIndex("PersonDocument")
                        .HasDatabaseName("ix_users_person_document");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Entities.Experience", b =>
                {
                    b.HasBaseType("Entities.Study");

                    b.Property<string>("PersonDocument")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("person_document");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("experience_position");

                    b.HasIndex("PersonDocument")
                        .HasDatabaseName("ix_experiences_person_document");

                    b.ToTable("experiences");
                });

            modelBuilder.Entity("Entities.ProjectEvaluation", b =>
                {
                    b.HasBaseType("Entities.ProposalEvaluation");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_evaluation_qualification");

                    b.ToTable("project_evaluation");
                });

            modelBuilder.Entity("Entities.Student", b =>
                {
                    b.HasBaseType("Entities.Person");

                    b.Property<string>("CreditNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("student_credit_number");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("student_program_code");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_code");

                    b.Property<string>("ProposalCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("proposal_code");

                    b.HasIndex("ProjectCode")
                        .HasDatabaseName("ix_student_project_code");

                    b.HasIndex("ProposalCode")
                        .HasDatabaseName("ix_student_proposal_code");

                    b.ToTable("student");
                });

            modelBuilder.Entity("Entities.Teacher", b =>
                {
                    b.HasBaseType("Entities.Person");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("teacher_position");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("Entities.City", b =>
                {
                    b.HasOne("Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cities_departments_department_code");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_people_countries_country_code");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Entities.Study", b =>
                {
                    b.HasOne("Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studies_cities_city_code");

                    b.HasOne("Entities.Person", null)
                        .WithMany("Studies")
                        .HasForeignKey("PersonDocument1")
                        .HasConstraintName("fk_studies_people_person_document1");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Entities.SublineInvestigation", b =>
                {
                    b.HasOne("Entities.LineInvestigation", null)
                        .WithMany("SublinesInvestigation")
                        .HasForeignKey("LineInvestigationCode")
                        .HasConstraintName("fk_sublines_lines_line_investigation_code");
                });

            modelBuilder.Entity("Entities.ThematicArea", b =>
                {
                    b.HasOne("Entities.SublineInvestigation", null)
                        .WithMany("ThematicAreas")
                        .HasForeignKey("SublineInvestigationCode")
                        .HasConstraintName("fk_thematic_areas_sublines_subline_investigation_code");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.HasOne("Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_people_person_document");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Experience", b =>
                {
                    b.HasOne("Entities.Study", null)
                        .WithOne()
                        .HasForeignKey("Entities.Experience", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experiences_studies_study_code");

                    b.HasOne("Entities.Person", null)
                        .WithMany("Experiences")
                        .HasForeignKey("PersonDocument")
                        .HasConstraintName("fk_experiences_people_person_document");
                });

            modelBuilder.Entity("Entities.ProjectEvaluation", b =>
                {
                    b.HasOne("Entities.ProposalEvaluation", null)
                        .WithOne()
                        .HasForeignKey("Entities.ProjectEvaluation", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_evaluation_proposal_evaluation_proposal_evaluation_c");
                });

            modelBuilder.Entity("Entities.Student", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Entities.Student", "Document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_people_person_document");

                    b.HasOne("Entities.Project", null)
                        .WithMany("Students")
                        .HasForeignKey("ProjectCode")
                        .HasConstraintName("fk_student_projects_project_code");

                    b.HasOne("Entities.Proposal", null)
                        .WithMany("Students")
                        .HasForeignKey("ProposalCode")
                        .HasConstraintName("fk_student_proposals_proposal_code");
                });

            modelBuilder.Entity("Entities.Teacher", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Entities.Teacher", "Document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_people_person_document");
                });

            modelBuilder.Entity("Entities.LineInvestigation", b =>
                {
                    b.Navigation("SublinesInvestigation");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entities.Proposal", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entities.SublineInvestigation", b =>
                {
                    b.Navigation("ThematicAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
