// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(PegiDbContext))]
    [Migration("20220704200033_Person")]
    partial class Person
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.City", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city_code");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city_name");

                    b.HasKey("Code");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("department_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("department_name");

                    b.HasKey("Code");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<int>("Document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("person_document");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_dateBirth");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_placeBirth");

                    b.Property<string>("CityCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CivilState")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_civilState");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_firstLastName");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_firstName");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_identification");

                    b.Property<string>("InstitutionalMail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_institutionalMail");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_nationality");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_phone");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_secondLastName");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_secondName");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_sex");

                    b.HasKey("Document");

                    b.HasIndex("CityCode");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("people");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_role");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entities.City", b =>
                {
                    b.HasOne("Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityCode");

                    b.HasOne("Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode");

                    b.Navigation("City");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
